home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import home
from home import views
from order import views as OrderViews
from user import views as UserViews
from django.utils.translation import gettext_lazy as _

urlpatterns = [
    path('selectlanguage', views.selectlanguage, name='selectlanguage'),
    path('selectcurrency', views.selectcurrency, name='selectcurrency'),
    path('savelangcur', views.savelangcur, name='savelangcur'),
    path('i18n/', include('django.conf.urls.i18n')),
]


urlpatterns += i18n_patterns(
    path('currencies/', include('currencies.urls')),
    path(_('admin/'), admin.site.urls),
    path('', views.index, name='home'),
    path('home/', include('home.urls')),
    path('product/', include('product.urls')),
    path('order/', include('order.urls')),
    path('user/', include('user.urls'), name='user'),
    path('ckeditor/', include('ckeditor_uploader.urls')),


    path(_('about/'), views.aboutus, name='aboutus'),
    path(_('contact/'), views.contactus, name='contactus'),
    path('search/', views.search, name='search'),
    path('search_auto/', views.search_auto, name='search_auto'),
    path('category/<int:id>/<slug:slug>', views.category_products, name='category_products'),
    path('product/<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('shopcart/', OrderViews.shopcart, name='shopcart'),
    path('login/', UserViews.login_form, name='login'),
    path('logout/', UserViews.logout_func, name='logout'),
    path('signup/', UserViews.signup_form, name='signup'),
    path('faq/', views.faq, name='faq'),
    path('ajaxcolor/', views.ajaxcolor, name='ajaxcolor'),
    prefix_default_language=False,
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('addtoshopcart/<int:id>', views.addtoshopcart, name='addtoshopcart'),
    path('deletefromcart/<int:id>', views.deletefromcart, name='deletefromcart'),
    path('orderproduct/', views.orderproduct, name='orderproduct'),
]

order/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.forms import ModelForm

from product.models import Product, Variants


class ShopCart(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    variant = models.ForeignKey(Variants, on_delete=models.SET_NULL,blank=True, null=True) # relation with varinat
    quantity = models.IntegerField()

    def __str__(self):
        return self.product.title

    @property
    def price(self):
        return (self.product.price)

    @property
    def amount(self):
        return (self.quantity * self.product.price)

    @property
    def varamount(self):
        return (self.quantity * self.variant.price)


class ShopCartForm(ModelForm):
    class Meta:
        model = ShopCart
        fields = ['quantity']

class Order(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Preaparing', 'Preaparing'),
        ('OnShipping', 'OnShipping'),
        ('Completed', 'Completed'),
        ('Canceled', 'Canceled'),
    )
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    code = models.CharField(max_length=5, editable=False )
    full_name = models.CharField(max_length=100)
    
    phone = models.CharField(blank=True, max_length=20)
    address = models.CharField(blank=True, max_length=250)
    country = models.CharField(blank=True, max_length=250)
    
    email = models.EmailField(blank=True, max_length=200)
    total = models.FloatField()
    status=models.CharField(max_length=10,choices=STATUS,default='New')
    ip = models.CharField(blank=True, max_length=20)
    adminnote = models.CharField(blank=True, max_length=100)
    create_at=models.DateTimeField(auto_now_add=True)
    update_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.full_name

class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['full_name','email','address','phone', 'country']

class OrderProduct(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Canceled', 'Canceled'),
    )
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variant = models.ForeignKey(Variants, on_delete=models.SET_NULL,blank=True, null=True) # relation with varinat
    quantity = models.IntegerField()
    price = models.FloatField()
    amount = models.FloatField()
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.title

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django.forms import TextInput, EmailInput, Select, FileInput

from user.models import UserProfile


class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length=30,label= 'User Name :')
    email = forms.EmailField(max_length=200,label= 'Email :')
    first_name = forms.CharField(max_length=100,label= 'First Name :')
    last_name = forms.CharField(max_length=100,label= 'Last Name :')

    class Meta:
        model = User
        fields = ('username', 'email','first_name','last_name', 'password1', 'password2', )

class UserUpdateForm(UserChangeForm):
    class Meta:
        model = User
        fields = ( 'username','email','first_name','last_name')
        widgets = {
            'username'  : TextInput(attrs={'class': 'input','placeholder':'username'}),
            'email'     : EmailInput(attrs={'class': 'input','placeholder':'email'}),
            'first_name': TextInput(attrs={'class': 'input','placeholder':'first_name'}),
            'last_name' : TextInput(attrs={'class': 'input','placeholder':'last_name' }),
        }

CITY = [
    ('Istanbul', 'Istanbul'),
    ('Ankara', 'Ankara'),
    ('Izmir', 'Izmir'),
]
class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('phone', 'address', 'city','country','image','language')
        widgets = {
            'phone'     : TextInput(attrs={'class': 'input','placeholder':'phone'}),
            'address'   : TextInput(attrs={'class': 'input','placeholder':'address'}),
            'city'      : Select(attrs={'class': 'input','placeholder':'city'},choices=CITY),
            'country'   : TextInput(attrs={'class': 'input','placeholder':'country' }),
            'image'     : FileInput(attrs={'class': 'input', 'placeholder': 'image', }),
        }

order/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.core.mail import send_mail
from django.conf import settings
from pypaystack import Transaction, Customer, Plan

# Create your views here.
from django.utils.crypto import get_random_string

from order.models import ShopCart, ShopCartForm, OrderForm, Order, OrderProduct
from product.models import Category, Product, Variants
from user.models import UserProfile


def index(request):
    return HttpResponse ("Order Page")

@login_required(login_url='/login') # Check login
def addtoshopcart(request,id):
    url = request.META.get('HTTP_REFERER')  # get last url
    current_user = request.user  # Access User Session information
    product= Product.objects.get(pk=id)

    if product.variant != 'None':
        variantid = request.POST.get('variantid')  # from variant add to cart
        checkinvariant = ShopCart.objects.filter(variant_id=variantid, user_id=current_user.id)  # Check product in shopcart
        if checkinvariant:
            control = 1 # The product is in the cart
        else:
            control = 0 # The product is not in the cart"""
    else:
        checkinproduct = ShopCart.objects.filter(product_id=id, user_id=current_user.id) # Check product in shopcart
        if checkinproduct:
            control = 1 # The product is in the cart
        else:
            control = 0 # The product is not in the cart"""

    if request.method == 'POST':  # if there is a post
        form = ShopCartForm(request.POST)
        if form.is_valid():
            if control==1: # Update  shopcart
                if product.variant == 'None':
                    data = ShopCart.objects.get(product_id=id, user_id=current_user.id)
                else:
                    data = ShopCart.objects.get(product_id=id, variant_id=variantid, user_id=current_user.id)
                data.quantity += form.cleaned_data['quantity']
                data.save()  # save data
            else : # Inser to Shopcart
                data = ShopCart()
                data.user_id = current_user.id
                data.product_id =id
                data.variant_id = variantid
                data.quantity = form.cleaned_data['quantity']
                data.save()
        messages.success(request, "Product added to Shopcart ")
        return HttpResponseRedirect(url)

    else: # if there is no post
        if control == 1:  # Update  shopcart
            data = ShopCart.objects.get(product_id=id, user_id=current_user.id)
            data.quantity += 1
            data.save()  #
        else:  #  Inser to Shopcart
            data = ShopCart()  # model ile bağlantı kur
            data.user_id = current_user.id
            data.product_id = id
            data.quantity = 1
            data.variant_id =None
            data.save()  #
        messages.success(request, "Product added to Shopcart")
        return HttpResponseRedirect(url)


def shopcart(request):
    category = Category.objects.all()
    current_user = request.user  # Access User Session information
    shopcart = ShopCart.objects.filter(user_id=current_user.id)
    total=0
    for rs in shopcart:
        total += rs.product.price * rs.quantity
    #return HttpResponse(str(total))
    context={'shopcart': shopcart,
             'category':category,
             'total': total,
             }
    return render(request,'shopcart_products.html',context)

@login_required(login_url='/login') # Check login
def deletefromcart(request,id):
    ShopCart.objects.filter(id=id).delete()
    messages.success(request, "Your item deleted form Shopcart.")
    return HttpResponseRedirect("/shopcart")


def orderproduct(request):
    category = Category.objects.all()
    current_user = request.user
    shopcart = ShopCart.objects.filter(user_id=current_user.id)
    total = 0
    for rs in shopcart:
        if rs.product.variant == 'None':
            total += rs.product.price * rs.quantity
        else:
            total += rs.variant.price * rs.quantity

    if request.method == 'POST':  # if there is a post
        form = OrderForm(request.POST)
        #return HttpResponse(request.POST.items())
        if form.is_valid():
            # Send Credit card to bank,  If the bank responds ok, continue, if not, show the error
            # ..............

            data = Order()
            data.full_name = form.cleaned_data['full_name'] #get product quantity from form
            data.email = form.cleaned_data['email']
            data.address = form.cleaned_data['address']
            # data.city = form.cleaned_data['city']
            data.phone = form.cleaned_data['phone']
            data.user_id = current_user.id
            data.total = total
            data.ip = request.META.get('REMOTE_ADDR')
            ordercode= get_random_string(5).upper() # random cod
            data.code =  ordercode
            data.save() 

            for rs in shopcart:
                detail = OrderProduct()
                detail.order_id     = data.id # Order Id
                detail.product_id   = rs.product_id
                detail.user_id      = current_user.id
                detail.quantity     = rs.quantity
                if rs.product.variant == 'None':
                    detail.price    = rs.product.price
                else:
                    detail.price = rs.variant.price
                detail.variant_id   = rs.variant_id
                detail.amount        = rs.amount
                detail.save()
                # ***Reduce quantity of sold product from Amount of Product
                if  rs.product.variant=='None':
                    product = Product.objects.get(id=rs.product_id)
                    product.amount -= rs.quantity
                    product.save()
                else:
                    variant = Variants.objects.get(id=rs.product_id)
                    variant.quantity -= rs.quantity
                    variant.save()
                #************ <> *****************
            # message = "Daclyns order info: /n " + " "+ data.full_name + " " +  data.phone + " " +  str(data.total) + " "+ str(ordercode) +" "+ data.address
            # send_mail('Order Form', message , settings.EMAIL_HOST_USER, ['dansokofi25@gmail.com'], fail_silently=False)

            ShopCart.objects.filter(user_id=current_user.id).delete() # Clear & Delete shopcart
            request.session['cart_items']=0
            messages.success(request, "Your Order has been completed. Thank you ")
            
            
            return render(request, 'Order_Completed.html',{'pk_public': settings.PAYSTACK_PUBLIC_KEY, 'ordercode':ordercode,'category': category, 'email': data.email, 'total': data.total})

            
            
        else:
            messages.warning(request, form.errors)
            return HttpResponseRedirect("/order/orderproduct")

    form= OrderForm()
    # profile = UserProfile.objects.get(user_id=current_user.id)
    context = {'shopcart': shopcart,
               'category': category,
               'total': total,
               'form': form,
            #    'pk_public': settings.PAYSTACK_PUBLIC_KEY,
            #    'profile': profile,
               }
    return render(request, 'Order_Form.html', context)

order/templates/Order_Completed.html
{% extends 'homebase.html' %}

{% block title %} Order Complated {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}

{% block sidebar %} {% include 'sidebar.html' %} {% endblock %}

{% block body %}

<div onload="payWithPaystack()">

  <script src="https://js.paystack.co/v1/inline.js"></script>
  <script>
    window.onload=function(){
      payWithPaystack();
      
    };
    function payWithPaystack(){
      let handler = PaystackPop.setup({
        key: "{{pk_public}}",
        email: "{{ email }}",
        amount: "{{ total }}" * 100,
        currency: 'GHS',
        ref: ""+Math.floor((Math.random()*10000000000)+1),

        onClose: function(){
          alert('Window Closed.');
        },
        callback: function(response){
          let message = 'Payment complete! Reference: ' + response.reference;
          alert(message);
        }
        
      });
      handler.openIframe();
    }

  </script>
</div>




    

    
    <!-- <div class="section" id="campaign-alert" style="display:none;">
 
        <div class="container">

            <div class="row">

                <div class="col-md-12"  id="paymentForm">
                    <div class="order-summary clearfix">
                        <div class="section-title">
                            <h3 class="title">Order Complated</h3>
                        </div>
                        <hr>
                        <h2>Dear  {{ user.full_name }}</h2>
                        <hr>
                        <h3>Your order is completed</h3>
                        <h3>Order Code : {{ ordercode }}</h3>
                        <h3>Thank You</h3>
                        <hr>
                    </div>

                </div>


            </div>
            
        </div>
        
    </div> -->
    
    

{% endblock %}

order/templates/Order_Form.html
{% extends 'homebase.html' %}
{% load currency %}
{% block title %} Order Page {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}

{% block sidebar %} {% include 'sidebar.html' %} {% endblock %}

{% block body %}

    <!-- BREADCRUMB -->
    
    <!-- /BREADCRUMB -->
    <!-- section -->
    <div class="section">
        <!-- container -->
        <div class="container" style="margin-top: 170px;>
            <!-- row -->
            <div  class="row">
                <Form action="" method="post" onsubmit="return submitForm(this);">
                    {% csrf_token %}
                    <div class="col-md-6">
                        <div class="billing-details">

                            <div class="section-title">
                                <h4 class="title">Shipping Details</h4>
                            </div>
                            <p><label for="id_full_name">Full name:</label>
                                <input type="text" name="full_name"  value="{{ user.full_name }}" class="input" required id="id_full_name"></p>
                            
                            <p><label for="id_email">Email Address:</label>
                                <input type="text" name="email"  value="{{ user.email }}" class="input" required id="id_email"></p>
                            <p><label for="id_last_name">Amount :</label>
                                <input type="number" name="total" value="{{ total }}" class="input" id="id_amount">
                            <p><label for="id_address">Address:</label>
                                <input type="text" name="address" value="{{ profile.address }}" class="input" maxlength="150" id="id_address"></p>
                            <p><label for="id_phone">Phone:</label>
                                <input type="text" name="phone"  value="{{ profile.phone }}"  class="input" maxlength="20" id="id_phone"></p>
                            <div class="pull-right">
                                <a href="{% url 'orderproduct' %}"><button  type="submit" class="primary-btn">Complete Order</button></a>
                            </div>
                        </div>
                    </div>

                    <!-- <div class="col-md-6">
                        <div class="shiping-methods">
                            <div class="section-title">
                                <h4 class="title">Payment Information</h4>
                            </div>
                            <p><label for="id_first_name">Total: {{ total }} USD </label>
                                <input type="text" name="total" class="input" readonly value="${{ total }} "></p>
                            <p><label for="id_first_name">Credit Card Holder</label>
                                <input type="text" name="holder" class="input"  value=""></p>
                            <p><label for="id_first_name">Credit Card Number</label>
                                <input type="text" name="number" class="input"  value=""></p>
                            <p><label for="id_first_name">Credit Exp Date/Year</label>
                                <input type="text" name="ecpdate" class="input"  placeholder="mm/yy"></p>
                            <p><label for="id_first_name">Security Number</label>
                                <input type="text" name="secnumber" class="input"  value=""></p>
                        </div>
                    </div> -->

                </Form>

                <div class="container " style="margin-top: 170px;">
                    <div class="row">
                      <main class="col-sm-9">
                        {% if shopcart.exists %}
                        <div class="card">
                          <table class="table table-hover shopping-cart-wrap cart-table">
                            <thead class="text-muted">
                              <tr>
                                <th scope="col">Product</th>
                                <th scope="col" width="120">Quantity</th>
                                <th scope="col" width="120">Price</th>
                                <th scope="col" width="200" class="text-right">Action</th>
                              </tr>
                            </thead>
                            <tbody class="cart-body">
                                {% for rs in shopcart %}
                              <tr class="cart-product">
                                <td>
                                    
                                  <a href="/product/{{ rs.product.id }}/{{ rs.product.slug }}">
                                    <figure class="media">
                                      <div class="img-wrap">
                                        {% if rs.variant.image_id  > 0 %}
                                        <img width="150"
                                          src="{{rs.variant.image }}"
                                          class="img-thumbnail img-sm"
                                        />
                                        {% else %}
                                        <img width="150"
                                          src="{{rs.product.image.url}}"
                                          class="img-thumbnail img-sm"
                                        />
                                        {% endif %}
                                      </div>
                  
                                      <figcaption class="media-body">
                                        <h6 class="title text-truncate">
                                          <a href="/product/{{ rs.product.id }}/{{ rs.product.slug }}">
                                            {{rs.product}} {{ rs.variant.size }} {{ rs.variant.color }}
                                          </a>
                                        </h6>
                                      </figcaption>
                                    </figure>
                                  </a>
                                </td>
                                <td>
                                    <div class="price-wrap">
                                      <var class="price">{{rs.quantity}}</var>
                                    
                                    </div>
                                    <!-- price-wrap .// -->
                                  </td>
                                <td>
                                  <div class="price-wrap">
                                    <var class="price">
                                    {% if rs.product.variant == 'None' %}
                                        {{ rs.product.price }} GH₵
                                    {% else %}
                                        {{ rs.variant.price }} GH₵
                                    {% endif %}</var>
                                  </div>
                                  <!-- price-wrap .// -->
                                </td>
                                <td class="text-right">
                                    <input class="cart-item-product-id" type="hidden" name="product_id" />
                                    <a href="/order/deletefromcart/{{ rs.id }}" onclick="return confirm('Delete ! Are you sure?')"><button class="btn btn-md  btn-outline-danger" type="submit">
                                      × Remove
                                    </button></a>
                                </td>
                              </tr>
                              {%endfor%}
                            </tbody>
                          </table>
                        </div>
                        <!-- card.// -->
                        {%else%}
                        <p class="lead">Cart is empty</p>
                        {%endif%}  
                      </main>
                  
                      <aside class="col-sm-3">
                        <!-- <dl class="dlist-align h5">
                          <dt>Sub total:</dt>
                          <dd class="text-right">GHC {{ cart.subtotal }}</dd>
                        </dl> -->
                        <dl class="dlist-align h5">
                          <dt>Total:</dt>
                          <dd class="text-right">
                            <strong
                              ><span class="cart-total">GH₵ {{ total }} </span></strong
                            >
                          </dd>
                        </dl>
                        <div class="text-wrap small text-muted">
                          Delivery fees not included yet.
                        </div>
                        <hr />
                        <tr>
                          <th colspan="2"></th>
                          <td>
                            <a class="btn btn-success btn-block" href="{% url 'orderproduct' %}"
                              >Buy</a
                            >
                          </td>
                        </tr>
                      </aside>
                    </div>
                </div>


            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /section -->
    <script>
      function submitForm() {
        return confirm('Are you sure you want to proceed to payment?');
      }
    </script>
    
    

{% endblock %}

order/templates/shopcart_products.html
{% extends 'homebase.html' %}
{% load currency %}
{% block title %} Shop Cart {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}

{% block sidebar %} {% include 'sidebar.html' %} {% endblock %}

{% block body %}

<div class="container " style="margin-top: 170px;">
    <div class="row">
      <main class="col-sm-9">
        {% if shopcart.exists %}
        <div class="card">
          <table class="table table-hover shopping-cart-wrap cart-table">
            <thead class="text-muted">
              <tr>
                <th scope="col">Product</th>
                <th scope="col" width="120">Quantity</th>
                <th scope="col" width="120">Price</th>
                <th scope="col" width="200" class="text-right">Action</th>
              </tr>
            </thead>
            <tbody class="cart-body">
                {% for rs in shopcart %}
              <tr class="cart-product">
                <td>
                    
                  <a href="/product/{{ rs.product.id }}/{{ rs.product.slug }}">
                    <figure class="media">
                      <div class="img-wrap">
                        {% if rs.variant.image_id  > 0 %}
                        <img width="150"
                          src="{{rs.variant.image }}"
                          class="img-thumbnail img-sm"
                        />
                        {% else %}
                        <img width="150"
                          src="{{rs.product.image.url}}"
                          class="img-thumbnail img-sm"
                        />
                        {% endif %}
                      </div>
  
                      <figcaption class="media-body">
                        <h6 class="title text-truncate">
                          <a href="/product/{{ rs.product.id }}/{{ rs.product.slug }}">
                            {{rs.product}} {{ rs.variant.size }} {{ rs.variant.color }}
                          </a>
                        </h6>
                      </figcaption>
                    </figure>
                  </a>
                </td>
                <td>
                    <div class="price-wrap">
                      <var class="price">{{rs.quantity}}</var>
                    
                    </div>
                    <!-- price-wrap .// -->
                  </td>
                <td>
                  <div class="price-wrap">
                    <var class="price"> 
                    {% if rs.product.variant == 'None' %}
                        {{ rs.product.price }} GH₵
                    {% else %}
                        {{ rs.variant.price }} GH₵
                    {% endif %}</var>
                  </div>
                  <!-- price-wrap .// -->
                </td>
                <td class="text-right">
                    <input class="cart-item-product-id" type="hidden" name="product_id" />
                    <a href="/order/deletefromcart/{{ rs.id }}" onclick="return confirm('Delete ! Are you sure?')"><button class="btn btn-md  btn-outline-danger" type="submit">
                      × Remove
                    </button></a>
                </td>
              </tr>
              {%endfor%}
            </tbody>
          </table>
        </div>
        <!-- card.// -->
        {%else%}
        <p class="lead">Cart is empty</p>
        {%endif%}  
      </main>
  
      <aside class="col-sm-3">
        <!-- <dl class="dlist-align h5">
          <dt>Sub total:</dt>
          <dd class="text-right">GHC {{ cart.subtotal }}</dd>
        </dl> -->
        <dl class="dlist-align h5">
          <dt>Total:</dt>
          <dd class="text-right">
            <strong
              >GH₵ <span class="cart-total">{{ total }} </span></strong
            >
          </dd>
        </dl>
        <div class="text-wrap small text-muted">
          Delivery fees not included yet.
        </div>
        <hr />
        <tr>
          <th colspan="2"></th>
          <td>
            <a class="btn btn-success btn-block" href="{% url 'orderproduct' %}"
              >Buy</a
            >
          </td>
        </tr>
      </aside>
    </div>
</div>

{% endblock %}